// emails/styles.ts

export const tokens = {
  colors: {
    black: '#000000',
    white: '#ffffff',
    bgGray: '#f2f2f2',
    cardBg: '#ffffff',
    lightGray: '#f5f5f5',
    borderGray: '#e6e6e6',
    textDark: '#3a3a3a',
    textMuted: '#6b6b6b',
    textLight: '#8a8a8a',
    accentGray: '#a0a0a0',
    amberBg: '#fff8e6',
    amberBorder: '#ffe599',
    amberText: '#8a5d00',
    greenBg: '#d1fae5',
    greenBorder: '#a7f3d0',
    greenText: '#065f46',
    redBg: '#fee2e2',
    redBorder: '#fca5a5',
    redText: '#991b1b',
    blueBg: '#dbeafe',
    blueBorder: '#93c5fd',
    blueText: '#1e40af',
  },
  fonts: {
    sans: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif",
    mono: "'Courier New', monospace",
  },
};

export const emailStyles = {
  body: `font-family: ${tokens.fonts.sans}; line-height: 1.6; color: ${tokens.colors.black}; background-color: ${tokens.colors.bgGray}; margin: 0; padding: 4% 2%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;`,
  wrapper: `width: 100%; max-width: 600px; margin: 0 auto; background: ${tokens.colors.cardBg}; border-radius: 24px; overflow: hidden; font-family: ${tokens.fonts.sans};`,
  header: `background: ${tokens.colors.black}; padding: 32px 20px; text-align: center;`,
  headerH1: `color: ${tokens.colors.white}; font-size: 24px; font-weight: 700; letter-spacing: 0.2em; text-transform: uppercase; margin: 0;`,
  headerSub: `color: ${tokens.colors.accentGray}; font-size: 10px; letter-spacing: 0.3em; text-transform: uppercase; margin-top: 6px; font-weight: 300;`,
  content: `padding: 6% 5% 5%;`,
  greeting: `font-size: 24px; font-weight: 600; letter-spacing: -0.02em; margin-bottom: 16px; color: ${tokens.colors.black}; line-height: 1.3;`,
  description: `color: ${tokens.colors.textDark}; font-size: 15px; line-height: 1.6; margin-bottom: 24px;`,
  credsBox: `background: ${tokens.colors.lightGray}; border-radius: 16px; padding: 20px; border: 1px solid ${tokens.colors.borderGray}; margin-bottom: 24px;`,
  credsLabel: `font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; color: ${tokens.colors.textMuted}; font-weight: 600; margin-bottom: 16px;`,
  credItem: `margin-bottom: 16px;`,
  credLabel: `font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; color: ${tokens.colors.textLight}; margin-bottom: 2px;`,
  credValue: `font-size: 16px; font-weight: 500; color: ${tokens.colors.black}; word-break: break-all;`,
  credPassword: `font-family: ${tokens.fonts.mono}; letter-spacing: 0.05em; font-weight: 700; background: ${tokens.colors.white}; padding: 6px 12px; border-radius: 40px; display: inline-block; border: 1px solid #d0d0d0; color: ${tokens.colors.black}; margin-top: 4px; font-size: 15px; max-width: 100%; word-break: break-all; box-sizing: border-box;`,
  btnWrap: `margin-top: 24px; text-align: center;`,
  btn: `display: inline-block; background: ${tokens.colors.black}; color: ${tokens.colors.white} !important; padding: 14px 32px; border-radius: 40px; font-size: 14px; font-weight: 600; letter-spacing: 0.02em; text-decoration: none; border: 1px solid ${tokens.colors.black}; box-sizing: border-box; max-width: 100%; text-align: center;`,
  bulletList: `margin: 16px 0; padding-left: 20px; color: ${tokens.colors.textDark}; font-size: 14px;`,
  bulletItem: `margin-bottom: 8px; line-height: 1.5;`,
  securityNote: `font-size: 12px; color: ${tokens.colors.textMuted}; font-style: italic; text-align: center; margin-top: 16px; margin-bottom: 24px;`,
  pillar: `margin-top: 16px; padding-top: 16px; border-top: 1px solid #eaeaea;`,
  pillarTitle: `font-size: 11px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; margin-bottom: 4px; color: #111;`,
  pillarText: `font-size: 13px; color: #6a6a6a; margin: 0; line-height: 1.5;`,
  footer: `background: #fafafa; padding: 24px 20px; border-top: 1px solid #ececec; text-align: center;`,
  copyright: `font-size: 9px; letter-spacing: 0.12em; color: #8f8f8f; text-transform: uppercase; line-height: 1.4;`,
  footerLinks: `margin-top: 12px; text-align: center;`,
  footerLink: `font-size: 10px; font-weight: 600; letter-spacing: 0.04em; text-transform: uppercase; color: #6f6f6f; text-decoration: none; display: inline-block; padding: 4px 8px;`,
  otpContainer: `background: ${tokens.colors.lightGray}; border-radius: 16px; padding: 24px; text-align: center; border: 1px dashed ${tokens.colors.borderGray}; margin: 24px 0;`,
  otpText: `font-family: ${tokens.fonts.mono}; font-size: 36px; font-weight: 700; letter-spacing: 0.15em; color: ${tokens.colors.black}; margin: 0; padding: 4px 0; max-width: 100%; word-break: break-all;`,
  noticeBox: `background: #fef2f2; border-left: 3px solid #ef4444; padding: 16px; border-radius: 8px; margin-bottom: 24px;`,
  noticeTitle: `font-size: 13px; font-weight: 600; color: #ef4444; margin-bottom: 4px;`,
  noticeText: `font-size: 13px; color: #555; line-height: 1.5;`,
};